#!/bin/bash
if [ -z "$1" ] || [ -z "$2" ]
    then echo "> mnohup script-file log-file"
    exit 1
fi
if [ "$1" == "$2" ]; then
    echo "you provided the same log-file name as script-file name"
    echo "use ${1}.log instead ..."
    #nohup matlab -nodisplay -nosplash < $1 > $1.log 2>&1 &
    nohup /opt/matlab/bin/matlab matlab -nodisplay -nosplash < $1 > $1.log 2>&1 &
    echo "$HOSTNAME: $!" > "${1}.log.$HOSTNAME.$!.pid"
    echo "$HOSTNAME: $!"
else
    #nohup matlab -nodisplay -nosplash < $1 > $2 2>&1 &
    nohup /opt/matlab/bin/matlab -nodisplay -nosplash < $1 > $2 2>&1 &
    echo "$HOSTNAME: $!" > "${2}.$HOSTNAME.$!.pid"
    echo "$HOSTNAME: $!"
fi  


