#!/bin/bash
if [ -z "$1" ] || [ -z "$2" ]; then
    echo "> rnohup script-file log-file"
    exit 1
fi

if [ "$1" == "$2" ]; then
    echo "log file must be different from script file and end with .log"
    exit 1

elif [ ${2: -4} != ".log" ]; then
    echo "log file must end with .log"
    exit 1

else
    nohup Rscript $1 > $2 2>&1 &
    echo "$HOSTNAME: $!" > "${2}.$HOSTNAME.$!.pid"
    echo "$HOSTNAME: $!"
fi

