#!/bin/bash

if [ -z "$1" ]; then
   echo
   echo "> slurm_wait jobid"
   echo
   exit
fi
        
if ! command -v scontrol &> /dev/null; then
    echo program scontrol not found
    exit
fi

if ! command -v hostname &> /dev/null; then
    echo program hostname not found
    exit
fi
    
if command -v host &> /dev/null; then
    hostname=$(host $(hostname)) 
    hostname=$(echo $hostname | cut -d' ' -f1)
else
    hostname=$(hostname)
fi
    
echo "scontrol show jobid -dd $1"
while sleep 1; do 
    status=$(scontrol show jobid -dd $1 | grep JobState) # "JobState=PENDING Reason=Resources Dependency=(null)"
    status=$(echo $status | cut -d' ' -f1) # "JobState=PENDING"
    status=$(echo $status | cut -d'=' -f2) # "PENDING" or "RUNNING"
    account=$(scontrol show jobid -dd $1 | grep Account) # "Priority=1 Nice=0 Account=ab1095 QOS=normal"
    account=$(echo $account | cut -d' ' -f3) # Account=ab1095
    account=$(echo $account | cut -d'=' -f2) # "ab1095"
    partition=$(echo $partition | cut -d'=' -f2) # "compute,compute2"
    partition=$(scontrol show jobid -dd $1 | grep Partition) # "Partition=compute,compute2 AllocNode:Sid=mlogin100:10034"
    partition=$(echo $partition | cut -d' ' -f1) # "Partition=compute,compute2"
    partition=$(echo $partition | cut -d'=' -f2) # "compute,compute2"
    echo "$(date): slurm job $1 account $account partition $partition submitted at $hostname: $status"
    if [ "$status" == "RUNNING" ]; then
        msg="slurm job $1 account $account partition $partition submitted at $hostname started!"
        if command -v zenity &> /dev/null; then # inform via small zenity GUI alert
            echo "run zenity ..."
            zenity --info --text="$msg"
        else # inform just in terminal
            echo "program zenity not found"
            echo $msg
        fi
        echo "stopping slurm_wait"
        exit
    fi # if job is running or not
done # while 

