#!/bin/bash

# link the files to your home if wanted

fs=(vimrc Rprofile) 

for i in "${fs[@]}"; do
    echo Run \" ln -sf $PWD/$i ~/.$i\"? [y/n]
    read yn
	if [ "$yn" != "${answer#[Yy]}" ] ;then
		ln -sf $PWD/$i ~/.$i
	else
		echo Do not link $i to ~/
	fi
done
