#!/bin/bash

## link the files to your home if wanted

# note: need to link this hook once by hand to the .git/hooks directory:
# ln -s /absolute/repopath/myhooks/post-merge /absolute/repopath/.git/hooks/.

fs=(vimrc Rprofile)
cnt=0

# enable user input in hook 
# from https://stackoverflow.com/questions/3417896/how-do-i-prompt-the-user-from-within-a-commit-msg-hook
exec < /dev/tty

# important: when the hook is called, $PWD is the repo main dir
echo "******** start  $PWD/myhooks/post-checkout ********"
for i in "${fs[@]}"; do
    cnt=$((cnt+1))
    echo $cnt/${#fs[@]}: run \"ln -sf $PWD/$i ~/.$i\"? [y/n]
    read yn
	if [ "$yn" != "${yn#[Yy]}" ] ;then
		ln -sf $PWD/$i ~/.$i
	fi
done
echo  "******** finish $PWD/myhooks/post-checkout ********"
