#!/bin/bash

## link the files to your home if wanted

# note: need to link this hook once by hand to the .git/hooks directory:
# ln -s <repodir>/myhook/post-merge <repodir>/.git/hooks/.

fs=(vimrc Rprofile) 

# enable user input ()
exec < /dev/tty

for i in "${fs[@]}"; do
    echo [$PWD/post-merge]: run \"ln -sf $PWD/../$i ~/.$i\"? [y/n]
    read yn
	if [ "$yn" != "${yn#[Yy]}" ] ;then
		ln -sf $PWD/../$i ~/.$i
	fi
done
